linters-settings:
  decorder:
    # Required order of `type`, `const`, `var` and `func` declarations inside a file.
    # Default: types before constants before variables before functions.
    dec-order:
      - type
      - const
      - var
      - func
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    lines: 120
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 40
    # Ignore comments when counting lines.
    # Default false
    ignore-comments: false

linters:
  disable-all: true
  enable:
    - bodyclose
#    - dupl temporary
    - errcheck
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck # this needs better research
    - copyloopvar
    - errorlint
    - funlen
    - goconst
    - gosec
    - lll
    - misspell
    - nilerr
    - noctx
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wsl
    - gci
    - unused
    - ineffassign
    - errcheck
    - gosimple
    - govet
    - staticcheck
run:
  issues-exit-code: 1